name = "chamak-store"
main = "src/index.js"
compatibility_date = "2026-10-08"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "chamak-store-db"
database_id = "758d41ec-670c-4b4f-93c0-0fe7a9a2ee30"
migrations_dir = "migrations"
